// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protocol/kingdom/realm/v1/realm_api.proto

package realmv1

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/lyft/protoc-gen-validate/validate"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RealmCreateRequest struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealmCreateRequest) Reset()         { *m = RealmCreateRequest{} }
func (m *RealmCreateRequest) String() string { return proto.CompactTextString(m) }
func (*RealmCreateRequest) ProtoMessage()    {}
func (*RealmCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f214aa5cc9b6b498, []int{0}
}

func (m *RealmCreateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *RealmCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RealmCreateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *RealmCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealmCreateRequest.Merge(m, src)
}

func (m *RealmCreateRequest) XXX_Size() int {
	return m.Size()
}

func (m *RealmCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RealmCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RealmCreateRequest proto.InternalMessageInfo

func (m *RealmCreateRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type RealmGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RealmGetRequest) Reset()         { *m = RealmGetRequest{} }
func (m *RealmGetRequest) String() string { return proto.CompactTextString(m) }
func (*RealmGetRequest) ProtoMessage()    {}
func (*RealmGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f214aa5cc9b6b498, []int{1}
}

func (m *RealmGetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *RealmGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RealmGetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *RealmGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealmGetRequest.Merge(m, src)
}

func (m *RealmGetRequest) XXX_Size() int {
	return m.Size()
}

func (m *RealmGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RealmGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RealmGetRequest proto.InternalMessageInfo

func (m *RealmGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RealmUpdateRequest struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label                *types.StringValue `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RealmUpdateRequest) Reset()         { *m = RealmUpdateRequest{} }
func (m *RealmUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*RealmUpdateRequest) ProtoMessage()    {}
func (*RealmUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f214aa5cc9b6b498, []int{2}
}

func (m *RealmUpdateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *RealmUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RealmUpdateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *RealmUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealmUpdateRequest.Merge(m, src)
}

func (m *RealmUpdateRequest) XXX_Size() int {
	return m.Size()
}

func (m *RealmUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RealmUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RealmUpdateRequest proto.InternalMessageInfo

func (m *RealmUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RealmUpdateRequest) GetLabel() *types.StringValue {
	if m != nil {
		return m.Label
	}
	return nil
}

type SingleRealmResponse struct {
	Entity               *Realm   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRealmResponse) Reset()         { *m = SingleRealmResponse{} }
func (m *SingleRealmResponse) String() string { return proto.CompactTextString(m) }
func (*SingleRealmResponse) ProtoMessage()    {}
func (*SingleRealmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f214aa5cc9b6b498, []int{3}
}

func (m *SingleRealmResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *SingleRealmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SingleRealmResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *SingleRealmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRealmResponse.Merge(m, src)
}

func (m *SingleRealmResponse) XXX_Size() int {
	return m.Size()
}

func (m *SingleRealmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRealmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRealmResponse proto.InternalMessageInfo

func (m *SingleRealmResponse) GetEntity() *Realm {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*RealmCreateRequest)(nil), "kingdom.realm.v1.RealmCreateRequest")
	proto.RegisterType((*RealmGetRequest)(nil), "kingdom.realm.v1.RealmGetRequest")
	proto.RegisterType((*RealmUpdateRequest)(nil), "kingdom.realm.v1.RealmUpdateRequest")
	proto.RegisterType((*SingleRealmResponse)(nil), "kingdom.realm.v1.SingleRealmResponse")
}

func init() {
	proto.RegisterFile("pkg/protocol/kingdom/realm/v1/realm_api.proto", fileDescriptor_f214aa5cc9b6b498)
}

var fileDescriptor_f214aa5cc9b6b498 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4d, 0x6b, 0x14, 0x31,
	0x18, 0xc7, 0xc9, 0x14, 0x47, 0x4d, 0x51, 0x4b, 0x14, 0x94, 0x45, 0x43, 0xbb, 0x28, 0x54, 0x61,
	0x33, 0xcc, 0x7a, 0xf4, 0x64, 0x15, 0x8b, 0xf4, 0xe0, 0x32, 0x65, 0x97, 0x22, 0x05, 0xc9, 0x76,
	0x9e, 0xa6, 0xa1, 0xd9, 0x49, 0xcc, 0x66, 0x57, 0xea, 0xcd, 0xaf, 0xe2, 0x49, 0xfc, 0x04, 0x1e,
	0x3d, 0x8a, 0x27, 0xbf, 0x80, 0xa0, 0xf3, 0x29, 0x3c, 0x4a, 0x93, 0x8c, 0x7d, 0x59, 0x17, 0xf6,
	0xd0, 0xdb, 0xf3, 0xf2, 0x7f, 0x7e, 0xcf, 0x4b, 0x82, 0x3b, 0xe6, 0x50, 0x64, 0xc6, 0x6a, 0xa7,
	0xf7, 0xb4, 0xca, 0x0e, 0x65, 0x25, 0x4a, 0x3d, 0xca, 0x2c, 0x70, 0x35, 0xca, 0xa6, 0x79, 0x30,
	0xde, 0x70, 0x23, 0x99, 0xd7, 0x90, 0x95, 0xa8, 0x60, 0x3e, 0xc1, 0xa6, 0x79, 0xab, 0x23, 0xa4,
	0x3b, 0x98, 0x0c, 0xd9, 0x9e, 0x1e, 0x65, 0x42, 0x0b, 0x1d, 0x60, 0xc3, 0xc9, 0xbe, 0xf7, 0xbc,
	0xe3, 0xad, 0x00, 0x68, 0x3d, 0x39, 0x25, 0x57, 0x47, 0xfb, 0x2e, 0xf6, 0xee, 0x08, 0xa8, 0x3a,
	0x53, 0xae, 0x64, 0xc9, 0x1d, 0x64, 0x33, 0x46, 0x2c, 0xa6, 0x42, 0x6b, 0xa1, 0xe0, 0xa4, 0xc5,
	0x3b, 0xcb, 0x8d, 0x01, 0x3b, 0x8e, 0xf9, 0x87, 0x0b, 0x2c, 0x13, 0xa4, 0xed, 0x47, 0x98, 0x14,
	0xc7, 0xee, 0x33, 0x0b, 0xdc, 0x41, 0x01, 0x6f, 0x27, 0x30, 0x76, 0xe4, 0x16, 0xbe, 0xa4, 0xf8,
	0x10, 0xd4, 0x1d, 0xb4, 0x8a, 0xd6, 0xaf, 0x16, 0xc1, 0x69, 0xaf, 0xe1, 0x1b, 0x5e, 0xbb, 0x09,
	0xae, 0x11, 0x5e, 0xc7, 0x89, 0x2c, 0xa3, 0x2a, 0x91, 0x65, 0x7b, 0x27, 0xe2, 0xfa, 0xa6, 0x3c,
	0x85, 0x3b, 0xa7, 0x22, 0xdd, 0x06, 0x9f, 0xac, 0xa2, 0xf5, 0xe5, 0xee, 0x5d, 0x16, 0xf6, 0x61,
	0xcd, 0x3e, 0x6c, 0xdb, 0x59, 0x59, 0x89, 0x01, 0x57, 0x13, 0x68, 0x9a, 0xbf, 0xc0, 0x37, 0xb7,
	0x65, 0x25, 0x14, 0x78, 0x7e, 0x01, 0x63, 0xa3, 0xab, 0x31, 0x90, 0x0c, 0xa7, 0x50, 0x39, 0xe9,
	0x8e, 0x3c, 0x7e, 0xb9, 0x7b, 0x9b, 0x9d, 0x7f, 0x19, 0x16, 0x0a, 0xa2, 0xac, 0xfb, 0x33, 0xc1,
	0x57, 0x7c, 0xe4, 0x69, 0xef, 0x25, 0xe9, 0xe3, 0x34, 0x2c, 0x4e, 0xee, 0xcf, 0xa9, 0x3b, 0x73,
	0x97, 0xd6, 0x83, 0x59, 0xd5, 0xff, 0x86, 0x7a, 0x85, 0x97, 0x36, 0xc1, 0x91, 0xb5, 0x39, 0xcc,
	0x93, 0xfb, 0x2d, 0x0a, 0xec, 0xe3, 0x34, 0x5c, 0x74, 0xee, 0x9c, 0x67, 0x0e, 0xbe, 0x28, 0xb6,
	0xc0, 0xe9, 0x73, 0x50, 0xe0, 0xe0, 0xe2, 0x46, 0xdd, 0xf8, 0x80, 0xfe, 0xfc, 0xa6, 0xe8, 0x53,
	0x4d, 0xd1, 0x97, 0x9a, 0xa2, 0xaf, 0x35, 0x45, 0xdf, 0x6a, 0x8a, 0x7e, 0xd4, 0x14, 0xfd, 0xaa,
	0x29, 0xc2, 0xf7, 0xb4, 0x15, 0xec, 0x3d, 0x54, 0xd2, 0x1d, 0x70, 0x3b, 0x43, 0xdc, 0xb8, 0x16,
	0x9e, 0xc6, 0xc8, 0xde, 0xf1, 0x57, 0xe8, 0xa1, 0xd7, 0x97, 0x7d, 0x6a, 0x9a, 0x7f, 0x4c, 0x96,
	0xb6, 0x8a, 0x9d, 0xcf, 0xc9, 0xca, 0x56, 0x2c, 0xf1, 0x42, 0x36, 0xc8, 0xbf, 0xff, 0x0b, 0xed,
	0xfa, 0xd0, 0xee, 0x20, 0x1f, 0xa6, 0xfe, 0x23, 0x3d, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0xcc, 0xca, 0x9f, 0xd5, 0x03, 0x00, 0x00,
}

func (this *RealmCreateRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RealmCreateRequest)
	if !ok {
		that2, ok := that.(RealmCreateRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func (this *RealmGetRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RealmGetRequest)
	if !ok {
		that2, ok := that.(RealmGetRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func (this *RealmUpdateRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RealmUpdateRequest)
	if !ok {
		that2, ok := that.(RealmUpdateRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if !this.Label.Equal(that1.Label) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func (this *SingleRealmResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SingleRealmResponse)
	if !ok {
		that2, ok := that.(SingleRealmResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Entity.Equal(that1.Entity) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RealmAPIClient is the client API for RealmAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RealmAPIClient interface {
	// Create a realm.
	Create(ctx context.Context, in *RealmCreateRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error)
	// Get a realm by id.
	Get(ctx context.Context, in *RealmGetRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error)
	// Update realm attributes.
	Update(ctx context.Context, in *RealmUpdateRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error)
	// Delete a realm by id.
	Delete(ctx context.Context, in *RealmGetRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error)
}

type realmAPIClient struct {
	cc *grpc.ClientConn
}

func NewRealmAPIClient(cc *grpc.ClientConn) RealmAPIClient {
	return &realmAPIClient{cc}
}

func (c *realmAPIClient) Create(ctx context.Context, in *RealmCreateRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error) {
	out := new(SingleRealmResponse)
	err := c.cc.Invoke(ctx, "/kingdom.realm.v1.RealmAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realmAPIClient) Get(ctx context.Context, in *RealmGetRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error) {
	out := new(SingleRealmResponse)
	err := c.cc.Invoke(ctx, "/kingdom.realm.v1.RealmAPI/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realmAPIClient) Update(ctx context.Context, in *RealmUpdateRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error) {
	out := new(SingleRealmResponse)
	err := c.cc.Invoke(ctx, "/kingdom.realm.v1.RealmAPI/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realmAPIClient) Delete(ctx context.Context, in *RealmGetRequest, opts ...grpc.CallOption) (*SingleRealmResponse, error) {
	out := new(SingleRealmResponse)
	err := c.cc.Invoke(ctx, "/kingdom.realm.v1.RealmAPI/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealmAPIServer is the server API for RealmAPI service.
type RealmAPIServer interface {
	// Create a realm.
	Create(context.Context, *RealmCreateRequest) (*SingleRealmResponse, error)
	// Get a realm by id.
	Get(context.Context, *RealmGetRequest) (*SingleRealmResponse, error)
	// Update realm attributes.
	Update(context.Context, *RealmUpdateRequest) (*SingleRealmResponse, error)
	// Delete a realm by id.
	Delete(context.Context, *RealmGetRequest) (*SingleRealmResponse, error)
}

func RegisterRealmAPIServer(s *grpc.Server, srv RealmAPIServer) {
	s.RegisterService(&_RealmAPI_serviceDesc, srv)
}

func _RealmAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealmCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealmAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.realm.v1.RealmAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealmAPIServer).Create(ctx, req.(*RealmCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealmAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealmGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealmAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.realm.v1.RealmAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealmAPIServer).Get(ctx, req.(*RealmGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealmAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealmUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealmAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.realm.v1.RealmAPI/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealmAPIServer).Update(ctx, req.(*RealmUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealmAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RealmGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealmAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.realm.v1.RealmAPI/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealmAPIServer).Delete(ctx, req.(*RealmGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RealmAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kingdom.realm.v1.RealmAPI",
	HandlerType: (*RealmAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RealmAPI_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RealmAPI_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RealmAPI_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RealmAPI_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protocol/kingdom/realm/v1/realm_api.proto",
}

func (m *RealmCreateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RealmCreateRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Label) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRealmApi(dAtA, i, uint64(len(m.Label)))
		i += copy(dAtA[i:], m.Label)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RealmGetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RealmGetRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRealmApi(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *RealmUpdateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RealmUpdateRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRealmApi(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.Label != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRealmApi(dAtA, i, uint64(m.Label.Size()))
		n1, err := m.Label.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SingleRealmResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SingleRealmResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Entity != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRealmApi(dAtA, i, uint64(m.Entity.Size()))
		n2, err := m.Entity.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintRealmApi(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}

func NewPopulatedRealmCreateRequest(r randyRealmApi, easy bool) *RealmCreateRequest {
	this := &RealmCreateRequest{}
	this.Label = string(randStringRealmApi(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedRealmApi(r, 2)
	}
	return this
}

func NewPopulatedRealmGetRequest(r randyRealmApi, easy bool) *RealmGetRequest {
	this := &RealmGetRequest{}
	this.Id = string(randStringRealmApi(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedRealmApi(r, 2)
	}
	return this
}

func NewPopulatedRealmUpdateRequest(r randyRealmApi, easy bool) *RealmUpdateRequest {
	this := &RealmUpdateRequest{}
	this.Id = string(randStringRealmApi(r))
	if r.Intn(10) != 0 {
		this.Label = types.NewPopulatedStringValue(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedRealmApi(r, 3)
	}
	return this
}

func NewPopulatedSingleRealmResponse(r randyRealmApi, easy bool) *SingleRealmResponse {
	this := &SingleRealmResponse{}
	if r.Intn(10) != 0 {
		this.Entity = NewPopulatedRealm(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedRealmApi(r, 2)
	}
	return this
}

type randyRealmApi interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneRealmApi(r randyRealmApi) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}

func randStringRealmApi(r randyRealmApi) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneRealmApi(r)
	}
	return string(tmps)
}

func randUnrecognizedRealmApi(r randyRealmApi, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldRealmApi(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}

func randFieldRealmApi(dAtA []byte, r randyRealmApi, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateRealmApi(dAtA, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		dAtA = encodeVarintPopulateRealmApi(dAtA, uint64(v2))
	case 1:
		dAtA = encodeVarintPopulateRealmApi(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateRealmApi(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateRealmApi(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateRealmApi(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}

func encodeVarintPopulateRealmApi(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}

func (m *RealmCreateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovRealmApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RealmGetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRealmApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RealmUpdateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRealmApi(uint64(l))
	}
	if m.Label != nil {
		l = m.Label.Size()
		n += 1 + l + sovRealmApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SingleRealmResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Entity != nil {
		l = m.Entity.Size()
		n += 1 + l + sovRealmApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovRealmApi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}

func sozRealmApi(x uint64) (n int) {
	return sovRealmApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *RealmCreateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRealmApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RealmCreateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RealmCreateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRealmApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRealmApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRealmApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RealmGetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRealmApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RealmGetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RealmGetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRealmApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRealmApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRealmApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *RealmUpdateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRealmApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RealmUpdateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RealmUpdateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRealmApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRealmApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRealmApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRealmApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Label == nil {
				m.Label = &types.StringValue{}
			}
			if err := m.Label.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRealmApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SingleRealmResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRealmApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SingleRealmResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SingleRealmResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRealmApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRealmApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entity == nil {
				m.Entity = &Realm{}
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRealmApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRealmApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipRealmApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRealmApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRealmApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRealmApi
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthRealmApi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRealmApi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRealmApi(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthRealmApi
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRealmApi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRealmApi   = fmt.Errorf("proto: integer overflow")
)
