// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protocol/kingdom/user/v1/user_api.proto

package userv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UserCreateRequest struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{0}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}

func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}

func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}

func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}

func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type SingleUserResponse struct {
	Entity               *User    `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleUserResponse) Reset()         { *m = SingleUserResponse{} }
func (m *SingleUserResponse) String() string { return proto.CompactTextString(m) }
func (*SingleUserResponse) ProtoMessage()    {}
func (*SingleUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{1}
}

func (m *SingleUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleUserResponse.Unmarshal(m, b)
}

func (m *SingleUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleUserResponse.Marshal(b, m, deterministic)
}

func (m *SingleUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleUserResponse.Merge(m, src)
}

func (m *SingleUserResponse) XXX_Size() int {
	return xxx_messageInfo_SingleUserResponse.Size(m)
}

func (m *SingleUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleUserResponse proto.InternalMessageInfo

func (m *SingleUserResponse) GetEntity() *User {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*UserCreateRequest)(nil), "kingdom.user.v1.UserCreateRequest")
	proto.RegisterType((*SingleUserResponse)(nil), "kingdom.user.v1.SingleUserResponse")
}

func init() {
	proto.RegisterFile("pkg/protocol/kingdom/user/v1/user_api.proto", fileDescriptor_67b5744c76a08e3b)
}

var fileDescriptor_67b5744c76a08e3b = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2e, 0xc8, 0x4e, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0xcf, 0xce, 0xcc, 0x4b, 0x4f, 0xc9, 0xcf,
	0xd5, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2f, 0x33, 0x04, 0xd3, 0xf1, 0x89, 0x05, 0x99, 0x7a, 0x60,
	0x15, 0x42, 0xfc, 0x50, 0x79, 0x3d, 0x90, 0xb8, 0x5e, 0x99, 0xa1, 0x94, 0x3a, 0x41, 0xdd, 0x10,
	0x9d, 0x4a, 0x9a, 0x5c, 0x82, 0xa1, 0xc5, 0xa9, 0x45, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x39, 0x89, 0x49, 0xa9, 0x39, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x33, 0x97, 0x50, 0x70, 0x66, 0x5e, 0x7a,
	0x4e, 0x2a, 0x48, 0x43, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x2e, 0x17, 0x5b,
	0x6a, 0x5e, 0x49, 0x66, 0x49, 0x25, 0x58, 0x31, 0xb7, 0x91, 0xa8, 0x1e, 0x9a, 0x5b, 0xf4, 0xc0,
	0xca, 0xa1, 0x8a, 0x8c, 0x62, 0xb8, 0xd8, 0x41, 0x7c, 0xc7, 0x00, 0x4f, 0xa1, 0x40, 0x2e, 0x36,
	0x88, 0xb5, 0x42, 0x4a, 0x58, 0xf5, 0xa0, 0xb8, 0x49, 0x4a, 0x19, 0x43, 0x0d, 0xa6, 0x63, 0x9c,
	0x12, 0xb8, 0x64, 0xf2, 0x8b, 0xd2, 0xf5, 0xaa, 0x52, 0xf3, 0x32, 0x4b, 0x32, 0x12, 0x8b, 0xd0,
	0xb5, 0x38, 0xf1, 0x80, 0xed, 0x2e, 0xc8, 0x0c, 0x00, 0xf9, 0x3d, 0x80, 0x31, 0x8a, 0x0d, 0x24,
	0x51, 0x66, 0xb8, 0x88, 0x89, 0xd9, 0x3b, 0x34, 0x62, 0x15, 0x13, 0xbf, 0x37, 0x54, 0x3d, 0x48,
	0x99, 0x5e, 0x98, 0xe1, 0x29, 0xb8, 0x48, 0x0c, 0x48, 0x24, 0x26, 0xcc, 0x30, 0x89, 0x0d, 0x1c,
	0x6c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xa9, 0xa9, 0x99, 0x9f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserAPIClient is the client API for UserAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserAPIClient interface {
	// Create a user.
	Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*SingleUserResponse, error)
}

type userAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserAPIClient(cc *grpc.ClientConn) UserAPIClient {
	return &userAPIClient{cc}
}

func (c *userAPIClient) Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*SingleUserResponse, error) {
	out := new(SingleUserResponse)
	err := c.cc.Invoke(ctx, "/kingdom.user.v1.UserAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAPIServer is the server API for UserAPI service.
type UserAPIServer interface {
	// Create a user.
	Create(context.Context, *UserCreateRequest) (*SingleUserResponse, error)
}

func RegisterUserAPIServer(s *grpc.Server, srv UserAPIServer) {
	s.RegisterService(&_UserAPI_serviceDesc, srv)
}

func _UserAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.user.v1.UserAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Create(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kingdom.user.v1.UserAPI",
	HandlerType: (*UserAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserAPI_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protocol/kingdom/user/v1/user_api.proto",
}
