// Code generated by protoc-gen-defaults. DO NOT EDIT.

package userv1

import (
	"context"
	"github.com/bxcodec/faker"
)

// MockUserAPIServer is the mock implementation of the UserAPIServer. Use this to create mock services that
// return random data. Useful in UI Testing.
type MockUserAPIServer struct{}

// Create is mock implementation of the method Create
func (MockUserAPIServer) Create(context.Context, *UserCreateRequest) (*SingleUserResponse, error) {
	var res SingleUserResponse
	if err := faker.FakeData(&res); err != nil {
		return nil, err
	}
	return &res, nil
}
