// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/protocol/kingdom/user/v1/user_api.proto

package userv1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/lyft/protoc-gen-validate/validate"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	RealmId              string   `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	Principal            string   `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetRealmId() string {
	if m != nil {
		return m.RealmId
	}
	return ""
}

func (m *CreateRequest) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

type GetRequest struct {
	RealmId              string   `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetRealmId() string {
	if m != nil {
		return m.RealmId
	}
	return ""
}

func (m *GetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateRequest struct {
	RealmId              string             `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	UserId               string             `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Secret               *types.StringValue `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{2}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetRealmId() string {
	if m != nil {
		return m.RealmId
	}
	return ""
}

func (m *UpdateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateRequest) GetSecret() *types.StringValue {
	if m != nil {
		return m.Secret
	}
	return nil
}

type SearchRequest struct {
	RealmId              *types.StringValue `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	UserId               *types.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Principal            *types.StringValue `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{3}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetRealmId() *types.StringValue {
	if m != nil {
		return m.RealmId
	}
	return nil
}

func (m *SearchRequest) GetUserId() *types.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SearchRequest) GetPrincipal() *types.StringValue {
	if m != nil {
		return m.Principal
	}
	return nil
}

type SingleResponse struct {
	Entity               *User    `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleResponse) Reset()         { *m = SingleResponse{} }
func (m *SingleResponse) String() string { return proto.CompactTextString(m) }
func (*SingleResponse) ProtoMessage()    {}
func (*SingleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{4}
}
func (m *SingleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleResponse.Unmarshal(m, b)
}
func (m *SingleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleResponse.Marshal(b, m, deterministic)
}
func (m *SingleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleResponse.Merge(m, src)
}
func (m *SingleResponse) XXX_Size() int {
	return xxx_messageInfo_SingleResponse.Size(m)
}
func (m *SingleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SingleResponse proto.InternalMessageInfo

func (m *SingleResponse) GetEntity() *User {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PaginatedResponse struct {
	Members              []*User  `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginatedResponse) Reset()         { *m = PaginatedResponse{} }
func (m *PaginatedResponse) String() string { return proto.CompactTextString(m) }
func (*PaginatedResponse) ProtoMessage()    {}
func (*PaginatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67b5744c76a08e3b, []int{5}
}
func (m *PaginatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginatedResponse.Unmarshal(m, b)
}
func (m *PaginatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginatedResponse.Marshal(b, m, deterministic)
}
func (m *PaginatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginatedResponse.Merge(m, src)
}
func (m *PaginatedResponse) XXX_Size() int {
	return xxx_messageInfo_PaginatedResponse.Size(m)
}
func (m *PaginatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaginatedResponse proto.InternalMessageInfo

func (m *PaginatedResponse) GetMembers() []*User {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "kingdom.user.v1.CreateRequest")
	proto.RegisterType((*GetRequest)(nil), "kingdom.user.v1.GetRequest")
	proto.RegisterType((*UpdateRequest)(nil), "kingdom.user.v1.UpdateRequest")
	proto.RegisterType((*SearchRequest)(nil), "kingdom.user.v1.SearchRequest")
	proto.RegisterType((*SingleResponse)(nil), "kingdom.user.v1.SingleResponse")
	proto.RegisterType((*PaginatedResponse)(nil), "kingdom.user.v1.PaginatedResponse")
}

func init() {
	proto.RegisterFile("pkg/protocol/kingdom/user/v1/user_api.proto", fileDescriptor_67b5744c76a08e3b)
}

var fileDescriptor_67b5744c76a08e3b = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xdf, 0x6a, 0x13, 0x4f,
	0x14, 0x66, 0x13, 0xd8, 0xfc, 0x7a, 0x7e, 0xc6, 0xe2, 0x82, 0x18, 0x63, 0xa8, 0x61, 0x6f, 0x2c,
	0x48, 0x66, 0x49, 0x55, 0x04, 0xbd, 0x50, 0xdb, 0x62, 0x0d, 0xf5, 0x22, 0x24, 0x24, 0x88, 0x14,
	0xea, 0x24, 0x7b, 0x3a, 0x19, 0xba, 0xd9, 0x19, 0x67, 0x27, 0x91, 0xf8, 0x38, 0x5e, 0xfa, 0x0a,
	0xbe, 0x81, 0x8f, 0xe4, 0x95, 0xec, 0xec, 0xe4, 0xef, 0xb6, 0x24, 0xe0, 0xd5, 0xcc, 0x39, 0xe7,
	0x3b, 0xdf, 0xf9, 0xe6, 0xcc, 0x07, 0x4f, 0xe5, 0x35, 0x0b, 0xa4, 0x12, 0x5a, 0x0c, 0x45, 0x14,
	0x5c, 0xf3, 0x98, 0x85, 0x62, 0x1c, 0x4c, 0x12, 0x54, 0xc1, 0xb4, 0x69, 0xce, 0x4b, 0x2a, 0x39,
	0x31, 0x08, 0x6f, 0xdf, 0xd6, 0x49, 0x9a, 0x27, 0xd3, 0x66, 0xb5, 0xc1, 0xb8, 0x1e, 0x4d, 0x06,
	0x64, 0x28, 0xc6, 0x01, 0x13, 0x4c, 0x64, 0x4c, 0x83, 0xc9, 0x95, 0x89, 0x4c, 0x60, 0x6e, 0x59,
	0x7f, 0xf5, 0xf5, 0x0a, 0x3c, 0x9a, 0x5d, 0x69, 0x3b, 0xb8, 0xc1, 0x30, 0x6e, 0x4c, 0x69, 0xc4,
	0x43, 0xaa, 0x31, 0xc8, 0x5d, 0x6c, 0xf3, 0x01, 0x13, 0x82, 0x45, 0xb8, 0x1c, 0xf1, 0x4d, 0x51,
	0x29, 0x51, 0x25, 0xb6, 0xfe, 0x64, 0xeb, 0x4b, 0x32, 0xa0, 0xff, 0x01, 0xca, 0x27, 0x0a, 0xa9,
	0xc6, 0x0e, 0x7e, 0x9d, 0x60, 0xa2, 0xbd, 0x87, 0xf0, 0x9f, 0x42, 0x1a, 0x8d, 0x2f, 0x79, 0x58,
	0x71, 0xea, 0xce, 0xe1, 0x5e, 0xa7, 0x64, 0xe2, 0x56, 0xe8, 0xd5, 0x60, 0x4f, 0x2a, 0x1e, 0x0f,
	0xb9, 0xa4, 0x51, 0xa5, 0x60, 0x6a, 0xcb, 0x84, 0xff, 0x16, 0xe0, 0x0c, 0xf5, 0x0e, 0x34, 0x0f,
	0xa0, 0x64, 0x56, 0xc9, 0x43, 0x4b, 0xe2, 0xa6, 0x61, 0x2b, 0xf4, 0x67, 0x50, 0xee, 0xc9, 0x70,
	0x37, 0x2d, 0xb7, 0x91, 0x78, 0xcf, 0xc1, 0x4d, 0x70, 0xa8, 0x50, 0x57, 0x8a, 0x75, 0xe7, 0xf0,
	0xff, 0xa3, 0x1a, 0xc9, 0x56, 0x45, 0xe6, 0xab, 0x22, 0x5d, 0xad, 0x78, 0xcc, 0xfa, 0x34, 0x9a,
	0x60, 0xc7, 0x62, 0xfd, 0x5f, 0x0e, 0x94, 0xbb, 0x48, 0xd5, 0x70, 0x34, 0x9f, 0xfd, 0x72, 0x63,
	0xf6, 0x36, 0xa6, 0x85, 0xb2, 0x17, 0xeb, 0xca, 0xb6, 0x2a, 0xb0, 0xba, 0x5f, 0xad, 0x2e, 0x77,
	0x17, 0xe9, 0x2b, 0xab, 0x7f, 0x03, 0x77, 0xbb, 0x3c, 0x66, 0x11, 0x76, 0x30, 0x91, 0x22, 0x4e,
	0xd0, 0x6b, 0x80, 0x8b, 0xb1, 0xe6, 0x7a, 0x66, 0xb5, 0xdf, 0x27, 0x1b, 0x6e, 0x25, 0xbd, 0x04,
	0x55, 0xc7, 0x82, 0xfc, 0x53, 0xb8, 0xd7, 0xa6, 0x8c, 0xc7, 0x54, 0x63, 0xb8, 0xe0, 0x08, 0xa0,
	0x34, 0xc6, 0xf1, 0x00, 0x55, 0x52, 0x71, 0xea, 0xc5, 0xdb, 0x49, 0xe6, 0xa8, 0xa3, 0x3f, 0x05,
	0x28, 0xa5, 0x99, 0x77, 0xed, 0x96, 0xd7, 0x02, 0x37, 0xf3, 0x95, 0x77, 0x90, 0xeb, 0x5a, 0x33,
	0x5c, 0xf5, 0x71, 0xae, 0xbe, 0xf1, 0x96, 0x13, 0x28, 0x9e, 0xa1, 0xf6, 0x1e, 0xe5, 0x70, 0x4b,
	0xbb, 0x6d, 0x27, 0x69, 0x81, 0x9b, 0x79, 0xeb, 0x06, 0x3d, 0x6b, 0xa6, 0xdb, 0x4e, 0xf5, 0x1e,
	0xdc, 0x53, 0x8c, 0x50, 0xe3, 0x3f, 0x4a, 0xfa, 0x08, 0x6e, 0x66, 0xb9, 0x1b, 0x24, 0xad, 0x79,
	0xb1, 0xea, 0xe7, 0xea, 0xb9, 0xdf, 0x3a, 0xfe, 0x02, 0x35, 0xa1, 0x18, 0xf9, 0x8e, 0x31, 0xd7,
	0x23, 0xaa, 0x36, 0x3b, 0x8e, 0xef, 0x98, 0x9f, 0x91, 0xbc, 0x9d, 0x7a, 0xa9, 0xed, 0x7c, 0x36,
	0xbe, 0x9b, 0x36, 0x7f, 0x14, 0x8a, 0xe7, 0xbd, 0x4f, 0x3f, 0x0b, 0xfb, 0xe7, 0x16, 0x9f, 0xc2,
	0x48, 0xbf, 0xf9, 0x7b, 0x91, 0xb9, 0x48, 0x33, 0x17, 0xfd, 0xe6, 0xc0, 0x35, 0x36, 0x7c, 0xf6,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x4d, 0x04, 0x3e, 0x26, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserAPIClient is the client API for UserAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserAPIClient interface {
	// Create an user identity.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SingleResponse, error)
	// Get an user by id.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SingleResponse, error)
	// Update user attributes.
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*SingleResponse, error)
	// Delete an user by id.
	Delete(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SingleResponse, error)
	// Search for user identity.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*PaginatedResponse, error)
}

type userAPIClient struct {
	cc *grpc.ClientConn
}

func NewUserAPIClient(cc *grpc.ClientConn) UserAPIClient {
	return &userAPIClient{cc}
}

func (c *userAPIClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SingleResponse, error) {
	out := new(SingleResponse)
	err := c.cc.Invoke(ctx, "/kingdom.user.v1.UserAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SingleResponse, error) {
	out := new(SingleResponse)
	err := c.cc.Invoke(ctx, "/kingdom.user.v1.UserAPI/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*SingleResponse, error) {
	out := new(SingleResponse)
	err := c.cc.Invoke(ctx, "/kingdom.user.v1.UserAPI/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) Delete(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*SingleResponse, error) {
	out := new(SingleResponse)
	err := c.cc.Invoke(ctx, "/kingdom.user.v1.UserAPI/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*PaginatedResponse, error) {
	out := new(PaginatedResponse)
	err := c.cc.Invoke(ctx, "/kingdom.user.v1.UserAPI/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAPIServer is the server API for UserAPI service.
type UserAPIServer interface {
	// Create an user identity.
	Create(context.Context, *CreateRequest) (*SingleResponse, error)
	// Get an user by id.
	Get(context.Context, *GetRequest) (*SingleResponse, error)
	// Update user attributes.
	Update(context.Context, *UpdateRequest) (*SingleResponse, error)
	// Delete an user by id.
	Delete(context.Context, *GetRequest) (*SingleResponse, error)
	// Search for user identity.
	Search(context.Context, *SearchRequest) (*PaginatedResponse, error)
}

func RegisterUserAPIServer(s *grpc.Server, srv UserAPIServer) {
	s.RegisterService(&_UserAPI_serviceDesc, srv)
}

func _UserAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.user.v1.UserAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.user.v1.UserAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.user.v1.UserAPI/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.user.v1.UserAPI/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Delete(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kingdom.user.v1.UserAPI/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kingdom.user.v1.UserAPI",
	HandlerType: (*UserAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserAPI_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserAPI_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserAPI_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserAPI_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _UserAPI_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protocol/kingdom/user/v1/user_api.proto",
}
